# Generated by Django 5.1 on 2024-08-13 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='location',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
