# Generated by Django 5.1 on 2024-08-13 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_author_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='author_picture',
        ),
        migrations.RemoveField(
            model_name='author',
            name='facebook_profile',
        ),
        migrations.RemoveField(
            model_name='author',
            name='linkedin_profile',
        ),
        migrations.RemoveField(
            model_name='author',
            name='location',
        ),
        migrations.RemoveField(
            model_name='author',
            name='twitter_handle',
        ),
        migrations.AddField(
            model_name='customuser',
            name='facebook_profile',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='linkedin_profile',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='twitter_handle',
            field=models.URLField(blank=True, null=True),
        ),
    ]
