# Generated by Django 5.1 on 2024-08-15 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_customuser_is_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['view_count'], name='cms_post_view_co_b2efe2_idx'),
        ),
    ]
