# Generated by Django 5.1 on 2024-08-15 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_post_view_count_post_cms_post_view_co_b2efe2_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='post',
            name='cms_post_search__9c25aa_idx',
        ),
        migrations.RemoveField(
            model_name='post',
            name='search_vector',
        ),
    ]
